### ISSUE TITLE
AdAway (4.0.9) will report success on update, while that's not the case. 

### ISSUE THREAD

**Issue by DenyDarko** [AdAway/AdAway#1066]
AdAway Wil report that it's up to date, however, an immediately update check will make it report that there are updates again. 

```
(Exception while downloading hosts file from https://hosts-file.net/ad_servers.txt.
java.io.EOFException: source exhausted prematurely
	at com.android.okhttp.okio.InflaterSource.read(InflaterSource.java:82)
	at com.android.okhttp.okio.GzipSource.read(GzipSource.java:80)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.adaway.model.hostsinstall.HostsInstallModel.downloadHostSource(HostsInstallModel.java:296)
	at ### org.adaway.model.hostsinstall.HostsInstallModel.downloadHostsSources(HostsInstallModel.java:248)
	at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2(HostsInstallViewModel.java:110)
	at org.adaway.ui.home.-$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764))
```

![screenshot_20180930-103816](https://user-images.githubusercontent.com/3320229/46254769-2d141300-c49d-11e8-80d2-3912e3e261ed.jpg)
![screenshot_20180930-103810](https://user-images.githubusercontent.com/3320229/46254770-2d141300-c49d-11e8-9bdc-e94c4d7ad5e9.jpg)

**Comment by DenyDarko** [comment]
It's not like I'm a specialist but based on what I read regarding the error (just Googled it), it's an issue from server side, hosts file in on this situation, however there are ways to workaround it, if ever happens.

**Comment by patrickdrd** [comment]
same here, I guess it doesn't know the dates of some sources, github ones included

**Comment by MarcAnt01** [comment]
After update message, when you go and apply hosts update, do you have 2/3 applied host sources 2/3?

**Comment by DenyDarko** [comment]
My Screenshot is already answering your question

**Comment by MarcAnt01** [comment]
Seen now, sorry, I'm just wondering why have both issues😂

**Comment by Tikotik** [comment]
Related to #1069 
Closed.
