### ISSUE TITLE
Copying of hosts file failed on Android 8 / Lineageos 15

### ISSUE THREAD

**Issue by scaidermern** [AdAway/AdAway#1091]
Android 8.1 Oreo, Lineageos 15.1 and AdAway 3.3.

Copying the hosts file to `/system/etc/hosts` fails. It turned out that I had to remount `/` as `rw` (not `/system` which is not a separate mountpoint):

`mount -orw,remount /`.

Afterwards copying the hosts file succeeded.

Not sure what AdAway can do here. Maybe add this to the troubleshooting section or even check permissions and offer to remount `/` or `/system` as `rw`.

**Comment by Vankog** [comment]
Please try the latest stable version instead. 
https://forum.xda-developers.com/showthread.php?t=2190753
Please note that F-Droid is not yet up to date due to some technical problems with their build system.

**Comment by scaidermern** [comment]
Nope, doesn't work either:

```
12-27 21:35:01.324 11360 11379 E AdAway  : Remounting as RO failed! Probably not a problem!
12-27 21:35:01.325 11360 11379 E AdAway  : Failed to update hosts file.
12-27 21:35:01.325 11360 11379 E AdAway  : org.adaway.model.hostsinstall.HostsInstallException: Unable to copy new private hosts file to target hosts file.
12-27 21:35:01.325 11360 11379 E AdAway  : 	at org.adaway.model.hostsinstall.HostsInstallModel.copyNewHostsFile(HostsInstallModel.java:465)
12-27 21:35:01.325 11360 11379 E AdAway  : 	at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:357)
12-27 21:35:01.325 11360 11379 E AdAway  : 	at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2(HostsInstallViewModel.java:123)
12-27 21:35:01.325 11360 11379 E AdAway  : 	at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
12-27 21:35:01.325 11360 11379 E AdAway  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
12-27 21:35:01.325 11360 11379 E AdAway  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
12-27 21:35:01.325 11360 11379 E AdAway  : 	at java.lang.Thread.run(Thread.java:764)
12-27 21:35:01.325 11360 11379 E AdAway  : Caused by: org.adaway.util.CommandException
12-27 21:35:01.325 11360 11379 E AdAway  : 	at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:169)
12-27 21:35:01.325 11360 11379 E AdAway  : 	at org.adaway.model.hostsinstall.HostsInstallModel.copyNewHostsFile(HostsInstallModel.java:449)
12-27 21:35:01.325 11360 11379 E AdAway  : 	... 6 more
```
