### ISSUE TITLE
Crash on Startup on Android 8.0 (OEM HTC) 

### ISSUE THREAD

**Issue by MDXDave** [AdAway/AdAway#1136]
The app crashes at startup with the following error:

>FATAL EXCEPTION: main
Process: org.adaway, PID: 13593
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.adaway/org.adaway.ui.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:524)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:30)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:69)
	at android.os.Handler.dispatchMessage(Unknown Source:21)
	at android.os.Looper.loop(Unknown Source:206)
	at android.app.ActivityThread.main(Unknown Source:113)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:224)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:556)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:519)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:467)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:141)
	at org.adaway.ui.MainActivity.onCreate(MainActivity.java:124)
	at android.app.Activity.performCreate(Unknown Source:3)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:466)
	... 9 more

Using Android 8.0 on the HTC U12+.
4.1.0 is working, 4.2.0 does not.

**Comment by MDXDave** [comment]
Sorry, my fault.
