### ISSUE TITLE
Enable ad-blocking not working - not enough space

### ISSUE THREAD

**Issue by Yky** [AdAway/AdAway#1226]
**Describe the bug**
When I click on "Enable ad-blocking" I get the error message "not enough space" even though the device has more than enough space. 

**To Reproduce**
1. Open Adaway
2. Click on "Enable ad-blocking"
3. See error "not enough space"

**Expected behavior**
Hosts file is written successfully

**Screenshots**

**Device**
 - AdAway version: 4.2.8
 - Device: Pixel 2
 - Android version: Android 9 (LineageOS 16)
 - Root version AddonSu

**Additional context**
`08-04 21:34:19.897 E/AdAway  (20292): Failed to update hosts file.
08-04 21:34:19.897 E/AdAway  (20292): org.adaway.model.hostsinstall.HostsInstallException: Unable to copy new private hosts file to target hosts file.
08-04 21:34:19.897 E/AdAway  (20292): 	at org.adaway.model.hostsinstall.HostsInstallModel.copyNewHostsFile(HostsInstallModel.java:555)
08-04 21:34:19.897 E/AdAway  (20292): 	at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:445)
08-04 21:34:19.897 E/AdAway  (20292): 	at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2$HostsInstallViewModel(HostsInstallViewModel.java:124)
08-04 21:34:19.897 E/AdAway  (20292): 	at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
08-04 21:34:19.897 E/AdAway  (20292): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-04 21:34:19.897 E/AdAway  (20292): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-04 21:34:19.897 E/AdAway  (20292): 	at java.lang.Thread.run(Thread.java:764)
08-04 21:34:19.897 E/AdAway  (20292): Caused by: org.adaway.util.RemountException: Remounting as RW failed! Probably not a problem!
08-04 21:34:19.897 E/AdAway  (20292): 	at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:158)
08-04 21:34:19.897 E/AdAway  (20292): 	at org.adaway.model.hostsinstall.HostsInstallModel.copyNewHostsFile(HostsInstallModel.java:539)
08-04 21:34:19.897 E/AdAway  (20292): 	... 6 more
`

**Comment by PerfectSlayer** [comment]
Hello @Yky,

Is your root addon allows to mount the system partition as a writable partition?
It seems `Caused by: org.adaway.util.RemountException: Remounting as RW failed!` is the issue here.

**Comment by Yky** [comment]
Yes, addonsu supports this. It also works on other devices.

**Comment by bulldozer2003** [comment]
I had the same issue until I connected my phone to my computer and ran `adb root && adb remount`. I also use AddonSu on Lineage as well but on a MotoX4. After those commands AdAway is able to successfully install the hosts file. Unfortunately I have to connect to adb and run the commands anytime I reboot the phone if I want to update the hosts file.

If this works then you have the same problem I reported in #1121. I am hoping to find an "on phone" workaround to avoid adb every reboot.

**Comment by PerfectSlayer** [comment]
Hum, if AdAway is not allowed to run `mount` commands, what about using `adb` to create a symlink and use it as target?

**Comment by Yky** [comment]
Works fine:

````
$ adb remount

Not running as root. Try "adb root" first.

$ adb root

restarting adbd as root

$ adb remount

remount succeeded

**Comment by gknoop** [comment]
Just chiming in to say I was having the same problem and the solution proposed by @Yky worked for me as well.

**Comment by PerfectSlayer** [comment]
AdAway does not use `adb remount` command but a `mount -o rw,remount <mount_point>` command in a root shell.

@Yky Could you:

1. _Enable verbose logging_ in the settings?
2. Restart the app (kill it from the recent app and start it again)
3. Try to install / update host
4. Post a logcat with the error and some of the logs above?

It should contains:
- The search of the mount point to remount,
- All the commands run in shell,
- And certainly some error codes which could help me to understand what is failing here.

It is good have someone which could help me to fix this issue because it is one of the most frequent and I can't reproduce it myself 😞  Thanks!

**Comment by Yky** [comment]
Sure, here you go:

> 08-14 17:40:15.687 11683 11707 V AdAway  : Downloading hosts file: https://adaway.org/hosts.txt
> 08-14 17:40:15.695 11683 11707 V AdAway  : Downloading hosts file: https://hosts-file.net/ad_servers.txt
> 08-14 17:40:15.849 11683 11707 V AdAway  : Downloading hosts file: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
> 08-14 17:40:15.856 11683 11707 D RootCommands: Starting Root Shell!
> 08-14 17:40:15.856 11683 11707 V RootCommands: No su in: /data/bin/
> 08-14 17:40:15.856 11683 11707 V RootCommands: No su in: /system/bin/
> 08-14 17:40:15.856 11683 11707 V RootCommands: No su in: /system/xbin/
> 08-14 17:40:15.856 11683 11707 V RootCommands: No su in: /sbin/
> 08-14 17:40:15.856 11683 11707 V RootCommands: No su in: /data/local/xbin/
> 08-14 17:40:15.856 11683 11707 V RootCommands: No su in: /data/local/bin/
> 08-14 17:40:15.856 11683 11707 V RootCommands: No su in: /system/sd/xbin/
> 08-14 17:40:15.856 11683 11707 V RootCommands: No su in: /system/bin/failsafe/
> 08-14 17:40:15.856 11683 11707 V RootCommands: No su in: /data/local/
> 08-14 17:40:15.856 11683 11707 V RootCommands: No su in: /su/bin/
> 08-14 17:40:15.856 11683 11707 D RootCommands: No su found in a well-known location, will just use "su".
> 08-14 17:40:15.856 11683 11707 D RootCommands: Starting shell: su
> 08-14 17:40:15.858 11683 11707 E AdAway  : Failed to update hosts file.
> 08-14 17:40:15.858 11683 11707 E AdAway  : org.adaway.model.hostsinstall.HostsInstallException: Failed to start a root shell.
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:456)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2$HostsInstallViewModel(HostsInstallViewModel.java:124)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at java.lang.Thread.run(Thread.java:764)
> 08-14 17:40:15.858 11683 11707 E AdAway  : Caused by: java.io.IOException: Cannot run program "su": error=13, Permission denied
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at java.lang.Runtime.exec(Runtime.java:695)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at java.lang.Runtime.exec(Runtime.java:525)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at org.sufficientlysecure.rootcommands.util.Utils.runWithEnv(Utils.java:99)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at org.sufficientlysecure.rootcommands.Shell.<init>(Shell.java:122)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at org.sufficientlysecure.rootcommands.Shell.startRootShell(Shell.java:54)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at org.sufficientlysecure.rootcommands.Shell.startRootShell(Shell.java:63)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:438)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	... 5 more
> 08-14 17:40:15.858 11683 11707 E AdAway  : Caused by: java.io.IOException: error=13, Permission denied
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at java.lang.UNIXProcess.forkAndExec(Native Method)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at java.lang.ProcessImpl.start(ProcessImpl.java:132)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
> 08-14 17:40:15.858 11683 11707 E AdAway  : 	... 12 more

**Comment by PerfectSlayer** [comment]
It is weird. According the log, you did not allow the app to use root.

> Failed to start a root shell.

Could you check your root manager app settings?

**Comment by Yky** [comment]
> It is weird. According the log, you did not allow the app to use root.
> 
> > Failed to start a root shell.
> 
> Could you check your root manager app settings?

According to the settings, root is enabled for AdAway and has been granted a number of times.

**Comment by Yky** [comment]
You're right. The su addon went missing after an update of the OS. I flashed it again now and it works. 

Now I get the same error message in AdAway, however, with a different exception: 

> 08-16 18:41:17.298 V/AdAway  ( 3100): Downloading hosts file: https://adaway.org/hosts.txt
> 08-16 18:41:17.309 V/AdAway  ( 3100): Downloading hosts file: https://hosts-file.net/ad_servers.txt
> 08-16 18:41:17.459 V/AdAway  ( 3100): Downloading hosts file: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
> 08-16 18:41:17.487 D/AdAway  ( 3100): Does not match: # AdAway default blocklist
> 08-16 18:41:17.487 D/AdAway  ( 3100): Does not match: # Blocking mobile ad providers and some analytics providers
> 08-16 18:41:17.487 D/AdAway  ( 3100): Does not match: # 
> 08-16 18:41:17.487 D/AdAway  ( 3100): Invalid IP address: #
> 08-16 18:41:17.487 D/AdAway  ( 3100): java.lang.IllegalArgumentException: '#' is not an IP string literal.
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at com.google.common.net.InetAddresses.formatIllegalArgumentException(InetAddresses.java:992)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at com.google.common.net.InetAddresses.forString(InetAddresses.java:143)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.util.RegexUtils.isValidIP(RegexUtils.java:80)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.util.HostsParser.parse(HostsParser.java:169)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.util.HostsParser.<init>(HostsParser.java:57)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.model.hostsinstall.HostsInstallModel.parseDownloadedHosts(HostsInstallModel.java:583)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.model.hostsinstall.HostsInstallModel.createNewHostsFile(HostsInstallModel.java:567)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:443)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2$HostsInstallViewModel(HostsInstallViewModel.java:124)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at java.lang.Thread.run(Thread.java:764)
> 08-16 18:41:17.487 D/AdAway  ( 3100): IP address is not valid: #
> 08-16 18:41:17.487 D/AdAway  ( 3100): Does not match: # Create an issue at https://github.com/AdAway/AdAway/issues
> 08-16 18:41:17.487 D/AdAway  ( 3100): Does not match: #
> 08-16 18:41:17.487 D/AdAway  ( 3100): Invalid IP address: #
> 08-16 18:41:17.487 D/AdAway  ( 3100): java.lang.IllegalArgumentException: '#' is not an IP string literal.
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at com.google.common.net.InetAddresses.formatIllegalArgumentException(InetAddresses.java:992)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at com.google.common.net.InetAddresses.forString(InetAddresses.java:143)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.util.RegexUtils.isValidIP(RegexUtils.java:80)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.util.HostsParser.parse(HostsParser.java:169)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.util.HostsParser.<init>(HostsParser.java:57)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.model.hostsinstall.HostsInstallModel.parseDownloadedHosts(HostsInstallModel.java:583)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.model.hostsinstall.HostsInstallModel.createNewHostsFile(HostsInstallModel.java:567)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:443)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2$HostsInstallViewModel(HostsInstallViewModel.java:124)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 08-16 18:41:17.487 D/AdAway  ( 3100): 	at java.lang.Thread.run(Thread.java:764)
> 08-16 18:41:17.487 D/AdAway  ( 3100): IP address is not valid: #
>

**Comment by PerfectSlayer** [comment]
Ok, I found an issue in the hosts comment parsing that I just fixed but it should not prevent the hosts file to be built and installed (it just sends a lot of traces in the logcat…).

It looks like the end of the logcat is missing. Are you sure you past everything here?
Because I only have log for the first steps of installation:
- 3 hosts to downloads,
- download the first one,
- parse the first one --> *your log stops here*
- download then parse the two other ones,
- build the merged hosts file,
- install the merged hosts file.

I think there is an issue in the last two steps. Could you check you don't have the end of the logcat? Thanks! 👍

**Comment by msfjarvis** [comment]
Magisk canaries will enforce non-writable `/system` on system-as-root devices so it'll be a good choice to start relying on a self-generated Magisk module or at least the one Magisk creates with the 'Systemless hosts' option. as a future-proof method of systemlessly installing hosts files.

**Comment by Yky** [comment]
Here's the entire log: https://gist.github.com/Yky/06ca508f37571a5766e26c5ecbac533c

Installing the hosts file fails as you expected. AdAway mounts back to RO before the exception occurs. 

> 08-17 16:35:17.229  3100  3169 I AdAway  : Remounting back to RO...
...
> 08-17 16:35:17.457  3100  3169 E AdAway  : Failed to update hosts file.
08-17 16:35:17.457  3100  3169 E AdAway  : org.adaway.model.hostsinstall.HostsInstallException: Unable to copy new private hosts file to target hosts file.
08-17 16:35:17.457  3100  3169 E AdAway  : 	at org.adaway.model.hostsinstall.HostsInstallModel.copyNewHostsFile(HostsInstallModel.java:555)
08-17 16:35:17.457  3100  3169 E AdAway  : 	at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:445)
08-17 16:35:17.457  3100  3169 E AdAway  : 	at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2$HostsInstallViewModel(HostsInstallViewModel.java:124)
08-17 16:35:17.457  3100  3169 E AdAway  : 	at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
08-17 16:35:17.457  3100  3169 E AdAway  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-17 16:35:17.457  3100  3169 E AdAway  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-17 16:35:17.457  3100  3169 E AdAway  : 	at java.lang.Thread.run(Thread.java:764)
08-17 16:35:17.457  3100  3169 E AdAway  : Caused by: org.adaway.util.RemountException: Remounting as RW failed! Probably not a problem!
08-17 16:35:17.457  3100  3169 E AdAway  : 	at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:158)
08-17 16:35:17.457  3100  3169 E AdAway  : 	at org.adaway.model.hostsinstall.HostsInstallModel.copyNewHostsFile(HostsInstallModel.java:539)
08-17 16:35:17.457  3100  3169 E AdAway  : 	... 6 more

**Comment by Yky** [comment]
The problem seems to be that _cat /proc/mounts_ does not return any mount points that start with _/system_. It follows from that, that the following command never returns true: 

https://github.com/AdAway/AdAway/blob/ccb82eae9178a1fabb4caa9ea4704d9ac71dfa99/libraries/RootCommands/src/main/java/org/sufficientlysecure/rootcommands/Remounter.java#L68

Hence, system is not remounted.

**Comment by Yky** [comment]
Since _/system_ is not in _/proc/mounts_, _"/"_ needs to be mounted instead to get RW on _/system_. 

Remounter compares mountpoints of different mounts from _/proc/mounts_.  The first one that has the mountpoint "/" is /dev/root. Then AdAways remounts /dev/root. This means _/system_ is still RO and hosts cannot be applied. AdAway needs to mount "/" instead in this case. 

https://github.com/AdAway/AdAway/blob/ccb82eae9178a1fabb4caa9ea4704d9ac71dfa99/libraries/RootCommands/src/main/java/org/sufficientlysecure/rootcommands/Remounter.java#L139

**Comment by PerfectSlayer** [comment]
Thanks for the full log.

There is a recursive algorithm to find the file to mount as RW.
It behaves as below:
1. Check if hosts file is in the mount entry points,
2. If yes, remount as RW and stop
3. If no, take parent path (`/system` then `/`) and repeat.

So if hosts file is a mount entry point, it will be remount.
If not, if `/system` is an entry point, it will be remount.
If not, `/` will be remount.

I don't think there is an issue with this behavior.
I am surprised we don't see any `RootCommands` tagged entry in the log file. Debug seems to be enabled but I can find any command run and `Remounter` log.

On my device, here is what we could find:
```
2019-08-18 11:24:16.156 10777-10834/org.adaway V/RootCommands: No su in: /data/bin/
2019-08-18 11:24:16.156 10777-10834/org.adaway V/RootCommands: No su in: /system/bin/
2019-08-18 11:24:16.156 10777-10834/org.adaway V/RootCommands: No su in: /system/xbin/
2019-08-18 11:24:16.156 10777-10834/org.adaway D/RootCommands: su found at: /sbin/
2019-08-18 11:24:16.156 10777-10834/org.adaway D/RootCommands: Starting shell: /sbin/su
2019-08-18 11:24:16.285 10777-11361/org.adaway D/RootCommands: Sending command(s): cat /proc/mounts 2>&1
2019-08-18 11:24:16.319 10777-11362/org.adaway D/RootCommands: ID: 0, Output: rootfs / rootfs ro,seclabel 0 0
2019-08-18 11:24:16.319 10777-11362/org.adaway D/RootCommands: ID: 0, Output: tmpfs /sbin tmpfs rw,seclabel,relatime,size=1509336k,nr_inodes=160506,mode=755 0 0
2019-08-18 11:24:16.320 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /sbin/.magisk/block/system /sbin/.magisk/mirror/system ext4 ro,seclabel,relatime,data=ordered 0 0
2019-08-18 11:24:16.320 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /sbin/.magisk/block/data /sbin/.magisk/mirror/data ext4 rw,seclabel,relatime,nobarrier,noauto_da_alloc,data=ordered 0 0
2019-08-18 11:24:16.320 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /sbin/.magisk/block/data /sbin/.magisk/modules ext4 rw,seclabel,relatime,nobarrier,noauto_da_alloc,data=ordered 0 0
2019-08-18 11:24:16.321 10777-11362/org.adaway D/RootCommands: ID: 0, Output: tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,size=1509336k,nr_inodes=160506,mode=755 0 0
2019-08-18 11:24:16.321 10777-11362/org.adaway D/RootCommands: ID: 0, Output: devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
2019-08-18 11:24:16.321 10777-11362/org.adaway D/RootCommands: ID: 0, Output: none /dev/memcg cgroup rw,relatime,memory 0 0
2019-08-18 11:24:16.322 10777-11362/org.adaway D/RootCommands: ID: 0, Output: none /dev/cpuctl cgroup rw,relatime,cpu 0 0
2019-08-18 11:24:16.322 10777-11362/org.adaway D/RootCommands: ID: 0, Output: none /dev/cpuset cgroup rw,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0
2019-08-18 11:24:16.322 10777-11362/org.adaway D/RootCommands: ID: 0, Output: none /dev/bfqio cgroup rw,relatime,bfqio 0 0
2019-08-18 11:24:16.322 10777-11362/org.adaway D/RootCommands: ID: 0, Output: adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
2019-08-18 11:24:16.323 10777-11362/org.adaway D/RootCommands: ID: 0, Output: proc /proc proc rw,relatime,gid=3009,hidepid=2 0 0
2019-08-18 11:24:16.323 10777-11362/org.adaway D/RootCommands: ID: 0, Output: sysfs /sys sysfs rw,seclabel,relatime 0 0
2019-08-18 11:24:16.323 10777-11362/org.adaway D/RootCommands: ID: 0, Output: selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
2019-08-18 11:24:16.324 10777-11362/org.adaway D/RootCommands: ID: 0, Output: debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
2019-08-18 11:24:16.324 10777-11362/org.adaway D/RootCommands: ID: 0, Output: pstore /sys/fs/pstore pstore rw,seclabel,relatime 0 0
2019-08-18 11:24:16.324 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /dev/block/platform/msm_sdcc.1/by-name/system /system ext4 ro,seclabel,relatime,data=ordered 0 0
2019-08-18 11:24:16.325 10777-11362/org.adaway D/RootCommands: ID: 0, Output: none /acct cgroup rw,relatime,cpuacct 0 0
2019-08-18 11:24:16.325 10777-11362/org.adaway D/RootCommands: ID: 0, Output: tmpfs /mnt tmpfs rw,seclabel,relatime,size=1509336k,nr_inodes=160506,mode=755,gid=1000 0 0
2019-08-18 11:24:16.326 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid 0 0
2019-08-18 11:24:16.326 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid 0 0
2019-08-18 11:24:16.330 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid 0 0
2019-08-18 11:24:16.331 10777-11362/org.adaway D/RootCommands: ID: 0, Output: none /config configfs rw,relatime 0 0
2019-08-18 11:24:16.331 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /dev/block/platform/msm_sdcc.1/by-name/cache /cache ext4 rw,seclabel,nosuid,nodev,noatime,data=ordered 0 0
2019-08-18 11:24:16.332 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /dev/block/platform/msm_sdcc.1/by-name/modem /firmware ext4 ro,context=u:object_r:firmware_file:s0,relatime,data=ordered 0 0
2019-08-18 11:24:16.332 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /dev/block/platform/msm_sdcc.1/by-name/persist /persist ext4 rw,seclabel,nosuid,nodev,relatime,data=ordered 0 0
2019-08-18 11:24:16.332 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /dev/block/platform/msm_sdcc.1/by-name/mdm1m9kefs3 /fsg ext4 ro,context=u:object_r:fsg_file:s0,nosuid,nodev,relatime 0 0
2019-08-18 11:24:16.333 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /dev/block/dm-0 /data ext4 rw,seclabel,nosuid,nodev,noatime,nodiratime,nobarrier,noauto_da_alloc,data=ordered 0 0
2019-08-18 11:24:16.333 10777-11362/org.adaway D/RootCommands: ID: 0, Output: tmpfs /storage tmpfs rw,seclabel,relatime,size=1509336k,nr_inodes=160506,mode=755,gid=1000 0 0
2019-08-18 11:24:16.333 10777-11362/org.adaway D/RootCommands: ID: 0, Output: /data/media /storage/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid 0 0
2019-08-18 11:24:16.334 10777-11362/org.adaway D/RootCommands: ID: 0, Output: tmpfs /storage/self tmpfs rw,seclabel,relatime,size=1509336k,nr_inodes=160506,mode=755,gid=1000 0 0
2019-08-18 11:24:16.335 10777-11362/org.adaway D/RootCommands: Command 0 finished.
2019-08-18 11:24:16.341 10777-10834/org.adaway D/RootCommands: ID: 0, ExitCode: 0
2019-08-18 11:24:16.342 10777-10834/org.adaway D/RootCommands: Remounting /system as rw
2019-08-18 11:24:16.342 10777-11325/org.adaway D/RootCommands: Sending command(s): busybox mount -o remount,rw /dev/block/platform/msm_sdcc.1/by-name/system /system 2>&1
    toolbox mount -o remount,rw /dev/block/platform/msm_sdcc.1/by-name/system /system 2>&1
    mount -o remount,rw /dev/block/platform/msm_sdcc.1/by-name/system /system 2>&1
    /system/bin/toolbox mount -o remount,rw /dev/block/platform/msm_sdcc.1/by-name/system /system 2>&1
    toybox mount -o rw,remount /dev/block/platform/msm_sdcc.1/by-name/system /system 2>&1
2019-08-18 11:24:16.344 10777-11326/org.adaway D/RootCommands: ID: 1, Output: /system/bin/sh: <stdin>[5]: busybox: not found
2019-08-18 11:24:16.371 10777-11326/org.adaway D/RootCommands: ID: 1, Output: mount: no such tool
2019-08-18 11:24:16.433 10777-11326/org.adaway D/RootCommands: ID: 1, Output: mount: no such tool
2019-08-18 11:24:16.485 10777-11326/org.adaway D/RootCommands: Command 1 finished.
2019-08-18 11:24:16.485 10777-10834/org.adaway D/RootCommands: ID: 1, ExitCode: 0
```

**Comment by Yky** [comment]
Here's a log that includes the RootCommands: https://gist.github.com/Yky/8632e3ce92c803c2e72fe66a7ea0fc0d

You can see that remounting "/" produces commands for remounting /dev/root

> 08-18 12:16:17.367 15904 15929 D RootCommands: Remounting / as rw
> 08-18 12:16:17.368 15904 16100 D RootCommands: Sending command(s): busybox mount -o remount,rw /dev/root / 2>&1
> 08-18 12:16:17.368 15904 16100 D RootCommands: toolbox mount -o remount,rw /dev/root / 2>&1
> 08-18 12:16:17.368 15904 16100 D RootCommands: mount -o remount,rw /dev/root / 2>&1
> 08-18 12:16:17.368 15904 16100 D RootCommands: /system/bin/toolbox mount -o remount,rw /dev/root / 2>&1
> 08-18 12:16:17.368 15904 16100 D RootCommands: toybox mount -o rw,remount /dev/root / 2>&1

**Comment by PerfectSlayer** [comment]
Okay, I understand better the situation here.
It looks like you have a system as root device and you are not using the Magisk systemless host module. So AdAway can't remount system as writable and is unable to install host.

As @msfjarvis said, you should consider having a look to magisk and its option to make hosts file writable. AdAway can't really do more here, except providing a better error message (it is not really a _not enough space_ issue).

**Comment by msfjarvis** [comment]
> As @msfjarvis said, you should consider having a look to magisk and its option to make hosts file writable. AdAway can't really do more here, except providing a better error message (it is not really a _not enough space_ issue).

Can the AdAway systemless mode be reworked to use the hosts module? I manually generate modules for a couple of my apps and it has served me well for over a year since I first deployed the code. I'll be happy to provide code samples if you need assistance with this.

**Comment by PerfectSlayer** [comment]
Could you tell me more about it?

Currently, there is a systemless detection code which tries to find what root solution is present and how to apply systemless modifications. The code could be found here: https://github.com/AdAway/AdAway/tree/master/app/src/main/java/org/adaway/util/systemless

In the next version, I did a lot of modifications about this part. First, I removed the old root/shell commands library and moved to John Wu's one. I also removed systemless detection / activation to rely only on Magisk systemless hosts option. So with v5:

* If you are root:
  * If your system is RW: OK
  * If your system is RO:
    * If Magisk used, enable Magisk systemless option: OK
    * If other root solution is used, find your own way to make it writable (really depends of the Android version, root used, etc…) or use non root mode
* If not root, use not root mode :)

The main idea here is to increase app stability and prevent issue like this one.
There is more and more devices moving to Magisk so I trim down other root systemless support (keep in mind other root mods will still work with RW /system).
Moreover, a non-root solution will also be provided for non-root user or compatibility issue.

But right now, I am still interested to improve Magisk systemless support or provide better support of Magisk in v5. So could you describe what think about "be reworked to use the hosts module"?

**Comment by boggle247** [comment]
I have this same problem from the initial post. On Pixel/sailfish running LineagOS 16 sept 2nd 2019 build. Using addon SU from Lineageos, and mindthegapps

**Comment by PerfectSlayer** [comment]
@boggle247 Did you try the latest version?

**Comment by boggle247** [comment]
4.2.9? Yes and I get the error:

      Copy failed. Copying of the hosts file failed! Please Read help for more information.

If I try changing the target host file from system/etc (what was used above) to data/data/hosts, it will successfully create the symlink and reboot. But then after reboot the hosts file listed as the default and when I hit "apply" again, it gets stuck on "applying host file changes" (something close to that anyway).

The permissions for my host file in system/etc are as shown in this screenshot: 
https://i.imgur.com/FJbJnhl.png

**Comment by boggle247** [comment]
@perfectslayer per u/chasilo on reddit, 

Open a terminal and type:

    su -
    mount -o rw,remount /

 So not close the terminal and then switch to adaway. Enable ad locking  And then it successfully wrote the hosts file. Rebooted and voila.

On 4.2.9 adaway for me. Haven't tested on 4.2.8 from fdroid.
