### ISSUE TITLE
java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by Killfrra** [AdAway/AdAway#1227]
When Tcpdump enabled and more than zero rules persist in 'Your lists' and clicking 'show results' app crashes with following error in logcat
```
FATAL EXCEPTION: main
Process: org.adaway, PID: 31220
java.lang.AbstractMethodError: abstract method "int org.adaway.ui.tcpdump.TcpdumpLogViewCallback.getColor(int)"
	at org.adaway.ui.tcpdump.TcpdumpLogAdapter.bindImageView(TcpdumpLogAdapter.java:75)
	at org.adaway.ui.tcpdump.TcpdumpLogAdapter.onBindViewHolder(TcpdumpLogAdapter.java:68)
	at org.adaway.ui.tcpdump.TcpdumpLogAdapter.onBindViewHolder(TcpdumpLogAdapter.java:25)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6936)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6978)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5895)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6162)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6001)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5997)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2227)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:613)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4032)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3749)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1898)
	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:412)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
	at android.view.Choreographer.doCallbacks(Choreographer.java:586)
	at android.view.Choreographer.doFrame(Choreographer.java:555)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5270)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:915)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:710)
```

**Comment by PerfectSlayer** [comment]
Hi @Killfrra 
Thanks for the bug report. I can't reproduce bug the stacktrace is helping a lot.

I will have to investigate more to find how to fix it (`getColor()` is not support to be abstract as it's part of the Android framewok).

Does it happens every time for you?
What is your app version and Android version?
Thanks!

**Comment by Killfrra** [comment]
Yes, I tried several times, and each time it was repeated.
App ver. 4.2.8 from F-Droid
Android ver. 5.1.1
Now and I can't reproduce this bug because I recently changed the root method from SuperSu to Magisk (19.3) and nothing works due to https://github.com/AdAway/AdAway/issues/1140
