### ISSUE TITLE
Enabling AdAway fails on 10/Q: "Remounting as RO failed"

### ISSUE THREAD

**Issue by woj-tek** [AdAway/AdAway#1481]
**Describe the bug**
Trying to enable AdAway fails: "The copy has failed"

**To Reproduce**
1. Open the app
2. Click: "enabled blocking of the ads"

**Device**
 - AdAway version: 4.3.0/F-droid
 - Device: OnePlus3
 - Android version: MSM Xtended XQ Release v4.0 [Q|Android 10.0]  (https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/cardinal-aosp-5-0-android-8-0-pre-t3693585)
 - Root version Magisk 20.1

**Additional context**

(this is with verbose debugging)
```
2019-12-17 09:12:12.280 29505-29505/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
2019-12-17 09:12:12.285 29505-29505/? I/AndroidRuntime: Using default boot image
2019-12-17 09:12:12.285 29505-29505/? I/AndroidRuntime: Leaving lock profiling enabled
2019-12-17 09:12:12.285 29470-29470/? I//system/bin/app_process: The ClassLoaderContext is a special shared library.
2019-12-17 09:12:12.290 29505-29505/? I//system/bin/app_process: Core platform API reporting enabled, enforcing=false
2019-12-17 09:12:12.311 29470-29470/? W//system/bin/app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
2019-12-17 09:12:12.319 29436-29436/? W//system/bin/app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
2019-12-17 09:12:12.331 29470-29470/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
2019-12-17 09:12:12.362 29436-29436/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
2019-12-17 09:12:12.405 29447-29447/? D/ICU: Time zone APEX file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
2019-12-17 09:12:12.425 26921-26967/? E/AdAway: Remounting as RO failed! Probably not a problem!
2019-12-17 09:12:12.429 29505-29505/? D/ICU: Time zone APEX file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
2019-12-17 09:12:12.433 29447-29447/? I//system/bin/app_process: The ClassLoaderContext is a special shared library.
2019-12-17 09:12:12.450 29505-29505/? I//system/bin/app_process: The ClassLoaderContext is a special shared library.
2019-12-17 09:12:12.465 29447-29447/? W//system/bin/app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
2019-12-17 09:12:12.472 26921-26967/? E/AdAway: Failed to update hosts file.
    org.adaway.model.hostsinstall.HostsInstallException: Unable to copy new private hosts file to target hosts file.
        at org.adaway.model.hostsinstall.HostsInstallModel.copyNewHostsFile(HostsInstallModel.java:560)
        at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:446)
        at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2$HostsInstallViewModel(HostsInstallViewModel.java:124)
        at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: org.adaway.util.CommandException
        at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:169)
        at org.adaway.model.hostsinstall.HostsInstallModel.copyNewHostsFile(HostsInstallModel.java:540)
        at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:446) 
        at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2$HostsInstallViewModel(HostsInstallViewModel.java:124) 
        at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2019-12-17 09:12:12.480 29505-29505/? W//system/bin/app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
2019-12-17 09:12:12.492 29505-29505/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
2019-12-17 09:12:12.494 29447-29447/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
2019-12-17 09:12:12.513 29470-29470/? D/AndroidRuntime: Shutting down VM
2019-12-17 09:12:12.553 29541-29541/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
2019-12-17 09:12:12.558 29541-29541/? I/AndroidRuntime: Using default boot image
2019-12-17 09:12:12.558 29541-29541/? I/AndroidRuntime: Leaving lock profiling enabled
2019-12-17 09:12:11.207 952-1095/? W/BatteryExternalStatsWorker: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
2019-12-17 09:12:12.562 952-952/? W/WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@a3d18ed
2019-12-17 09:12:12.563 29541-29541/? I//system/bin/app_process: Core platform API reporting enabled, enforcing=false
2019-12-17 09:12:12.582 29436-29436/? D/AndroidRuntime: Shutting down VM
2019-12-17 09:12:12.661 29505-29505/? D/AndroidRuntime: Shutting down VM
2019-12-17 09:12:12.695 29541-29541/? D/ICU: Time zone APEX file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
2019-12-17 09:12:12.718 29541-29541/? I//system/bin/app_process: The ClassLoaderContext is a special shared library.
2019-12-17 09:12:12.722 29447-29447/? D/AndroidRuntime: Shutting down VM
2019-12-17 09:12:12.749 29541-29541/? W//system/bin/app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
2019-12-17 09:12:12.759 29541-29541/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
2019-12-17 09:12:12.806 29541-29541/? D/AndroidRuntime: Shutting down VM
2019-12-17 09:12:12.844 952-1673/? W/NotificationService: Toast already killed. pkg=com.f8OPMCpketC1Mg7s callback=android.app.ITransientNotification$Stub$Proxy@1b29c6d
```

EDIT:
* app correctly asks for root access (and it's granted)
* remounting root partition (`mount -o rw,remount /`) allows me to manually edit the file from shell but still not from AdAway (same issue as above)
* using custom path `/etc/hosts` (`etc -> /system/etc`) doesn't exactly work (symlink to target is missing - but I'm weary about overriding it here:
```
2019-12-17 09:38:26.650 4396-4396/? I/ls: type=1400 audit(0.0:12031): avc: denied { ioctl } for path="pipe:[1747489]" dev="pipefs" ino=1747489 ioctlcmd=5413 scontext=u:r:magisk:s0 tcontext=u:object_r:magisk_file:s0 tclass=fifo_file permissive=1
2019-12-17 09:38:26.658 26921-26967/? E/AdAway: Failed to update hosts file.
    org.adaway.model.hostsinstall.HostsInstallException: The symlink to the hosts file target is missing.
        at org.adaway.model.hostsinstall.HostsInstallModel.applyHostsFile(HostsInstallModel.java:442)
        at org.adaway.ui.home.HostsInstallViewModel.lambda$update$2$HostsInstallViewModel(HostsInstallViewModel.java:124)
        at org.adaway.ui.home.-$$Lambda$HostsInstallViewModel$hr_O0jGNR8I8qQyGthIQYups81s.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by PerfectSlayer** [comment]
Hello @woj-tek 

Thanks for your detailed bug report.
When you said you successfully remount root partition, did you do it using an adb shell or another root app?
And about Magisk, did you enable the systemless hosts module?

**Comment by woj-tek** [comment]
Hi @PerfectSlayer 
I used adb shell and then used `su` do get to elevated command prompt (easier to type on the computer) and got prompt on the device to grant root access.

Regarding magisk - I dont use any modules (never used before up to Android 9) because I didn't know if that was needed (I still assume it's not?).

I can run any (well, almost ;) ) command against the device to help with the debugging.

**Comment by PerfectSlayer** [comment]
All details are included in the AdAway settings when you tried to enable the systemless feature from AdAway: https://github.com/AdAway/AdAway/commit/c6afddcb4174284767ce861e87ade4050a2ab48a#diff-01dafb3fd0217441330103cfc8300094

The commit you link was added because users don't often look at the AdAway settings (#1477). I guess there is still some room for improvement as you struggle to find it (and it's fine, not your fault 😅 ).

Glad everything is working for you!

**Comment by woj-tek** [comment]
Hmmm - I don't remember enabling that option, though I restored ad-away from TitaniumBackup and just clicked "apply" on the main screen.

Now I'm curious how I arrived at this state of configuration in AdAway :-D

**Comment by PerfectSlayer** [comment]
You can't enable it if you have Magisk: it will pops up a dialog to explain how to enable it from Magisk.
If you have other (older) root solution, like supersu or superuser, it will run some scripts to set it up properly.

But even if you can't enable it, it should show the correct module status.
It's helpful because Android 9+ requires it with system as root.

**Comment by woj-tek** [comment]
I think that was the problem - I switched from Nougat to Q/10 and restored AdAway from TB. As I said - I don't recall any pop-up/notification about systemless (maybe previous state was at work and logic to detect need for systemless was not triggered?) hence my struggle.

It seems that the case is an outlier and it should just work for normal usage :-)

Thanks for all the support!
