### ISSUE TITLE
failed to export backup

### ISSUE THREAD

**Issue by QingKongBaiYu** [AdAway/AdAway#1993]
**Describe the bug**
it shows a toaster "failed to export backup" when trying to backup to external storage. 
With 13 sources and few manual rules. 
happening on all 5.0.* version( include 5.0.3 ).

**To Reproduce**
1. Go to 'Preferences'
2. Go to 'Backup / restore block rules'
3. Click on 'backup'
4. See error, toaster "Failed to export backup", and no file created.

**Expected behavior**
success to export backup

**Screenshots**
![Screenshot_20200510-183550069](https://user-images.githubusercontent.com/45838887/81496836-2e4e2880-92ed-11ea-8290-84c7ba0b78e8.jpg)
![Screenshot_20200510-183621241](https://user-images.githubusercontent.com/45838887/81496838-327a4600-92ed-11ea-8072-da299f13002f.jpg)

**Device**
 - AdAway version: [5.0.1, 5.0.2, 5.0.3]
 - Device: [xiaomi Mi 9]
 - Android version: [Android 10]
 - Root version [Magisk 20.4]

**Additional context**
--------- beginning of main
05-10 18:38:30.104  9980 10099 D WorkerThreadMonitor: Kill MSF check result[ senderSize:0,sendInterval:126352,receiveInterval=28446,addCmdCount=1488
05-10 18:38:32.992   831   857 W ANDR-PERF-LM: FeatureState: readState() 149: warning: appName is NULL, returning default State
05-10 18:38:32.992   831   857 I chatty  : uid=0(root) lmCoreThread identical 1 line
05-10 18:38:32.992   831   857 W ANDR-PERF-LM: FeatureState: readState() 149: warning: appName is NULL, returning default State
05-10 18:38:32.995  2017  2017 D ImageWallpaper: wallpaper visibility changes to: true
05-10 18:38:33.078  2017  2017 V StatusBar: mStatusBarWindow: com.android.systemui.statusbar.phone.StatusBarWindowView{34a61c1 V.E...... ........ 0,0-1080,74} canPanelBeCollapsed(): false
05-10 18:38:33.080 20367 20367 I AndroidIME: AbstractIme.onDeactivate():145 PasswordIme.onDeactivate()
05-10 18:38:33.084   753  2044 I netd    : firewallSetUidRule(2, 10146, 2) <0.07ms>
--------- beginning of system
05-10 18:38:33.093  1418  1836 D ConnectivityService: Blocked status changed to true for 10146(1429) on netId 109
05-10 18:38:33.093  1418  1836 D ConnectivityService: Blocked status changed to true for 10146(1430) on netId 109
05-10 18:38:33.108  9770  9770 I PublicSearchService: Creating pss binder().
05-10 18:38:33.111  9770  9788 I PublicSearchService: Calling beginBinderSession().
05-10 18:38:33.111  9770  9788 I PublicSearchService: beginBinderSession(): calling binder
05-10 18:38:33.112  9770  9788 V AIEngines: #process
05-10 18:38:33.112  9770 11903 V AIEngines: #processSync
05-10 18:38:33.112  9770 11903 V AIEngines: #process: skip check - hasSuggestion? false, selectedengines []
05-10 18:38:33.112  9770 11903 V AIEngines: #process: done
05-10 18:38:33.146 11346 14235 I LocationReportEnabler: android::base::GetProperty: gsm.sim.operator.numeric -> 310030
05-10 18:38:33.637 31526 31526 I AiAiSuggestUi: Fetching contents @ null, isPrimaryTask = true
05-10 18:38:33.690  1418  1418 V SettingsProvider: Notifying for 0: content://settings/secure/reminder_exp_learning_time_elapsed
05-10 18:38:33.665 31526 31526 I chatty  : uid=10117(com.google.android.apps.nexuslauncher) identical 1 line
05-10 18:38:33.665 31526 31526 I AiAiSuggestUi: Fetching contents @ null, isPrimaryTask = true
05-10 18:38:33.744  9770  9819 W ThreadPoolDumper: Queue length for executor EventBus is now 11. Perhaps some tasks are too long, or the pool is too small.
05-10 18:38:33.747  9770  9819 W LocationOracle: No location history returned by ContextManager
05-10 18:38:33.755 11346 11346 I GeofencerStateMachine: sendNewLocationAvailability: availability=LocationAvailability[isLocationAvailable: false]
05-10 18:38:33.770  9770  9815 I StreamController: registerScope: nowcards-15-5b7f293-0ea3
05-10 18:38:33.772 11346 14235 I LocationReportEnabler: android::base::GetProperty: gsm.sim.operator.numeric -> 310030
05-10 18:38:33.776 11346 11346 I GeofencerStateMachine: sendNewLocationAvailability: availability=LocationAvailability[isLocationAvailable: false]
05-10 18:38:33.787  9770  9815 I MicroDetectionState: Should stop hotword detection immediately - false
05-10 18:38:33.788  9770  9815 I MicroDetectionState: Keep running DSP hotword
05-10 18:38:34.034   831  2904 E ANDR-PERF-LM: VmRssMeter:: start() 298: Could not find pid, can not collect vmrss data
05-10 18:38:34.034   831  2904 E ANDR-PERF-LM: AdaptiveLaunch: writeToDataBase() 63: Meter aborted or could not get meter data for this run
05-10 18:38:34.356  1418  3378 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.adaway/.ui.home.HomeActivity bnds=[37,1992][238,2328]} from uid 10117
05-10 18:38:34.359   831   857 W ANDR-PERF-LM: FeatureState: readState() 149: warning: appName is NULL, returning default State
05-10 18:38:34.364  1418  1446 W WindowManager: TaskSnapshotSurface.create: Failed to find main window for token=AppWindowToken{50499eb token=Token{566193a ActivityRecord{dd1d865 u0 org.adaway/.ui.home.HomeActivity t3624}}}
05-10 18:38:34.365  1418  1418 V SettingsProvider: Notifying for 0: content://settings/secure/reminder_exp_learning_time_elapsed
05-10 18:38:34.360   831   857 I chatty  : uid=0(root) lmCoreThread identical 1 line
05-10 18:38:34.360   831   857 W ANDR-PERF-LM: FeatureState: readState() 149: warning: appName is NULL, returning default State
05-10 18:38:34.369 12962 12962 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@e16d7eb
05-10 18:38:34.418 31526 31526 I AiAiSuggestUi: Clearing suggestions.
05-10 18:38:34.436  1418  1450 I ActivityTaskManager: Displayed org.adaway/.ui.home.HomeActivity: +77ms
05-10 18:38:34.437 31526 31526 I AiAiSuggestUi: Fetching contents @ null, isPrimaryTask = false
05-10 18:38:34.470  9770  9815 I MicroDetectionState: Should stop hotword detection immediately - false
05-10 18:38:34.541 31092  4720 W AiAiOverview: Timed out waiting for Bitmap ContentInfo to be updated.
05-10 18:38:34.788 31526 31526 I AiAiSuggestUi: Clearing suggestions.
05-10 18:38:34.795  2017  2017 D ImageWallpaper: wallpaper visibility changes to: false
05-10 18:38:34.803   877   877 E Layer   : [Surface(name=AppWindowToken{82a12ec token=Token{8fbc19f ActivityRecord{6eff3e u0 com.google.android.apps.nexuslauncher/.NexusLauncherActivity t3326}}})/@0xf263e4d - animation-leash#0] No local sync point found
05-10 18:38:34.803   877   877 E Layer   : [Surface(name=AppWindowToken{50499eb token=Token{566193a ActivityRecord{dd1d865 u0 org.adaway/.ui.home.HomeActivity t3624}}})/@0xd85bf4 - animation-leash#0] No local sync point found
05-10 18:38:34.816   877   877 E Layer   : [Surface(name=AppWindowToken{82a12ec token=Token{8fbc19f ActivityRecord{6eff3e u0 com.google.android.apps.nexuslauncher/.NexusLauncherActivity t3326}}})/@0xf263e4d - animation-leash#0] No local sync point found
05-10 18:38:34.817   877   877 E Layer   : [Surface(name=AppWindowToken{50499eb token=Token{566193a ActivityRecord{dd1d865 u0 org.adaway/.ui.home.HomeActivity t3624}}})/@0xd85bf4 - animation-leash#0] No local sync point found
05-10 18:38:34.852  9770  9864 I PBSessionCacheImpl: Deleted sessionId[42970503519477025] from persistence.
05-10 18:38:34.854  9770  9815 W SearchServiceCore: Abort, client detached.
05-10 18:38:34.854  9770  9815 W SearchServiceCore: Abort, client detached.
05-10 18:38:34.854  9770  9815 I StreamController: cleanUpControllerScope(nowcards-15-5b7f293-0ea3)
05-10 18:38:34.857  9770  9815 W SearchServiceCore: Abort, client detached.
05-10 18:38:35.397   831  2904 E ANDR-PERF-LM: VmRssMeter:: start() 298: Could not find pid, can not collect vmrss data
05-10 18:38:35.397   831  2904 E ANDR-PERF-LM: AdaptiveLaunch: writeToDataBase() 63: Meter aborted or could not get meter data for this run
05-10 18:38:35.673  1418 11352 I ActivityTaskManager: START u0 {cmp=org.adaway/.ui.prefs.PrefsActivity} from uid 10154
05-10 18:38:35.679   831   857 W ANDR-PERF-LM: FeatureState: readState() 149: warning: appName is NULL, returning default State
05-10 18:38:35.679   831   857 I chatty  : uid=0(root) lmCoreThread identical 1 line
05-10 18:38:35.679   831   857 W ANDR-PERF-LM: FeatureState: readState() 149: warning: appName is NULL, returning default State
05-10 18:38:35.685 12962 12962 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@db3e45a
05-10 18:38:36.167   753 16993 E ResolverController: No valid NAT64 prefix (109, <unspecified>/0)
05-10 18:38:36.703   831  2904 E ANDR-PERF-LM: VmRssMeter:: start() 298: Could not find pid, can not collect vmrss data
05-10 18:38:36.703   831  2904 E ANDR-PERF-LM: AdaptiveLaunch: writeToDataBase() 63: Meter aborted or could not get meter data for this run
05-10 18:38:38.088 12962 13088 E AdAway  : External storage can not be written.
05-10 18:38:38.129  1418  4555 E InputDispatcher: Window handle Window{cc2fffd u0 org.adaway/org.adaway.ui.prefs.PrefsActivity} has no registered input channel
05-10 18:38:38.794   810   810 I sensors-hal: flush:209, android.sensor.accelerometer/46
05-10 18:38:38.803   810   810 I sensors-hal: flush:215, android.sensor.accelerometer/46 completed
05-10 18:38:38.850  1418 11352 W AppOps  : Noting op not finished: uid 10099 pkg com.google.android.gms code 79 time=1589107096369 duration=-1
05-10 18:38:38.851 11346 11346 I TrustAgent: [PhonePositionTracker] Received AR result: DetectedActivity [type=9, confidence=0] at 1589107090019
05-10 18:38:38.857   831   857 W ANDR-PERF-LM: FeatureState: readState() 149: warning: appName is NULL, returning default State
05-10 18:38:38.857   831   857 I chatty  : uid=0(root) lmCoreThread identical 1 line
05-10 18:38:38.857   831   857 W ANDR-PERF-LM: FeatureState: readState() 149: warning: appName is NULL, returning default State
05-10 18:38:38.861  2017  2017 D ImageWallpaper: wallpaper visibility changes to: true
05-10 18:38:38.864  1418 11352 W AppOps  : Noting op not finished: uid 10099 pkg com.google.android.gms code 79 time=1589107118850 duration=0
05-10 18:38:38.867 11346 11346 I TrustAgent: [PhonePositionTracker] Received AR result: DetectedActivity [type=9, confidence=0] at 1589107106032
05-10 18:38:38.876  1418  4555 W AppOps  : Noting op not finished: uid 10099 pkg com.google.android.gms code 79 time=1589107118864 duration=0
05-10 18:38:38.881  1418  4555 W AppOps  : Noting op not finished: uid 10099 pkg com.google.android.gms code 79 time=1589107118876 duration=0
05-10 18:38:38.883  1418  4555 W AppOps  : Noting op not finished: uid 10099 pkg com.google.android.gms code 79 time=1589107118881 duration=0
05-10 18:38:38.927  2017  2017 V StatusBar: mStatusBarWindow: com.android.systemui.statusbar.phone.StatusBarWindowView{34a61c1 V.E...... ........ 0,0-1080,74} canPanelBeCollapsed(): false
05-10 18:38:39.496 31526 31526 I AiAiSuggestUi: Fetching contents @ null, isPrimaryTask = true
05-10 18:38:39.547  1418  1418 V SettingsProvider: Notifying for 0: content://settings/secure/reminder_exp_learning_time_elapsed
05-10 18:38:39.498 31526 31526 I chatty  : uid=10117(com.google.android.apps.nexuslauncher) identical 1 line
05-10 18:38:39.501 31526 31526 I AiAiSuggestUi: Fetching contents @ null, isPrimaryTask = true
05-10 18:38:39.581  9770  9828 W ThreadPoolDumper: Queue length for executor EventBus is now 11. Perhaps some tasks are too long, or the pool is too small.
05-10 18:38:39.596  9770  9815 I StreamController: registerScope: nowcards-15-5b7f293-0ea3
05-10 18:38:39.608  9770  9815 I MicroDetectionState: Should stop hotword detection immediately - false
05-10 18:38:39.609  9770  9815 I MicroDetectionState: Keep running DSP hotword
05-10 18:38:39.900   831  2904 E ANDR-PERF-LM: VmRssMeter:: start() 298: Could not find pid, can not collect vmrss data
05-10 18:38:39.900   831  2904 E ANDR-PERF-LM: AdaptiveLaunch: writeToDataBase() 63: Meter aborted or could not get meter data for this run
05-10 18:38:40.077 31526 31526 I AiAiSuggestUi: Clearing suggestions.
05-10 18:38:40.104 31526 31526 I AiAiSuggestUi: Fetching contents @ null, isPrimaryTask = false
05-10 18:38:40.210 31092  4720 W AiAiOverview: Timed out waiting for Bitmap ContentInfo to be updated.
05-10 18:38:40.260   831   857 W ANDR-PERF-LM: FeatureState: readState() 149: warning: appName is NULL, returning default State
05-10 18:38:40.260   831   857 I chatty  : uid=0(root) lmCoreThread identical 1 line
05-10 18:38:40.260   831   857 W ANDR-PERF-LM: FeatureState: readState() 149: warning: appName is NULL, returning default State
05-10 18:38:40.305   753  2044 I netd    : firewallSetUidRule(2, 10146, 1) <0.01ms>
05-10 18:38:40.267  1418  1418 V SettingsProvider: Notifying for 0: content://settings/secure/reminder_exp_learning_time_elapsed
05-10 18:38:40.306  1418  1836 D ConnectivityService: Blocked status changed to false for 10146(1429) on netId 109
05-10 18:38:40.306  1418  1836 D ConnectivityService: Blocked status changed to false for 10146(1430) on netId 109
05-10 18:38:40.311 20367 20367 I KeyboardViewUtil: KeyboardViewUtil.getKeyboardHeightRatio():128 systemKeyboardHeightRatio:1.000000; userKeyboardHeightRatio:1.000000.
05-10 18:38:40.313 20367 20367 I AndroidIME: AbstractIme.onActivate():83 PasswordIme.onActivate() : EditorInfo = Package = com.termux : Type = Text : Learning = Disable : Suggestion = Show : AutoCorrection = Disable : Microphone = Show : NoPersonalizedLearning = Disable : AutoStartVoiceInput = Disable, IncognitoMode = false
05-10 18:38:40.317 20367 20367 E KeyboardViewController: KeyboardViewController.show():432 Requesting to show sub view with id 2131428309(key_pos_password_header_numbers) which doesn't exist in current keyboard view
05-10 18:38:40.317 20367 20367 E KeyboardViewController: jsh
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at kev.a(PG:193)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at bps.a(PG:4)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at com.google.android.apps.inputmethod.latin.keyboard.LatinPasswordKeyboard.a(PG:19)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at jzc.a(PG:15)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at jyq.a(PG:31)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at jyq.H(PG:26)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at jyu.d(PG:10)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at jyu.b(PG:108)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at com.android.inputmethod.latin.LatinIME.b(PG:337)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at dqg.onStartInputView(PG:779)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at android.inputmethodservice.InputMethodService.startViews(InputMethodService.java:1955)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:1884)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:638)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:220)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at android.os.Handler.dispatchMessage(Handler.java:107)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at android.os.Looper.loop(Looper.java:214)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at android.app.ActivityThread.main(ActivityThread.java:7356)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at java.lang.reflect.Method.invoke(Native Method)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-10 18:38:40.317 20367 20367 E KeyboardViewController:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-10 18:38:40.317 20367 20367 W KeyboardModeManager: KeyboardModeManager.setInputView():302 setInputView() : inputView = com.google.android.apps.inputmethod.libs.framework.core.InputView{3f90733 V.E...... .......D 0,0-1080,2134}
05-10 18:38:40.317 20367 20367 I ConversationToQueryExtension: ConversationToQueryExtension.isEnabledForHostApp():252 Conv2Query not enabled due to current app [com.termux] not in whitelist
05-10 18:38:40.317 20367 20367 I ConversationToQueryExtension: ConversationToQueryExtension.onActivate():162 onActivate() : Disabled by unsupported host app
05-10 18:38:40.318 20367 20367 I VoiceImeExtension: VoiceImeExtension.shouldStartVoiceInputAutomatically():335 No private IME option set to start voice input.
05-10 18:38:40.371  9770  9815 I MicroDetectionState: Should stop hotword detection immediately - false
05-10 18:38:40.630 31526 31526 I AiAiSuggestUi: Clearing suggestions.
05-10 18:38:40.634  2017  2017 D ImageWallpaper: wallpaper visibility changes to: false
05-10 18:38:40.643   877   877 E Layer   : [Surface(name=AppWindowToken{5e8c1c1 token=Token{da142a8 ActivityRecord{af2acb u0 com.termux/.app.TermuxActivity t3625}}})/@0x94634a1 - animation-leash#0] No local sync point found
05-10 18:38:40.643   877   877 E Layer   : [Surface(name=AppWindowToken{5e8c1c1 token=Token{da142a8 ActivityRecord{af2acb u0 com.termux/.app.TermuxActivity t3625}}})/@0x94634a1 - animation-leash#0] No local sync point found
05-10 18:38:40.644   877   877 E Layer   : [Surface(name=AppWindowToken{82a12ec token=Token{8fbc19f ActivityRecord{6eff3e u0 com.google.android.apps.nexuslauncher/.NexusLauncherActivity t3326}}})/@0xf263e4d - animation-leash#0] No local sync point found
05-10 18:38:40.644   877   877 E Layer   : [Surface(name=AppWindowToken{82a12ec token=Token{8fbc19f ActivityRecord{6eff3e u0 com.google.android.apps.nexuslauncher/.NexusLauncherActivity t3326}}})/@0xf263e4d - animation-leash#0] No local sync point found
05-10 18:38:40.687  9770  9864 I PBSessionCacheImpl: Deleted sessionId[42970503519477026] from persistence.
05-10 18:38:40.698  9770  9815 W SearchServiceCore: Abort, client detached.
05-10 18:38:40.698  9770  9815 W SearchServiceCore: Abort, client detached.
05-10 18:38:40.700  9770  9815 I StreamController: cleanUpControllerScope(nowcards-15-5b7f293-0ea3)
05-10 18:38:40.701  9770  9815 W SearchServiceCore: Abort, client detached.
05-10 18:38:41.311   831  2904 E ANDR-PERF-LM: VmRssMeter:: start() 298: Could not find pid, can not collect vmrss data
05-10 18:38:41.311   831  2904 E ANDR-PERF-LM: AdaptiveLaunch: writeToDataBase() 63: Meter aborted or could not get meter data for this run
05-10 18:38:41.667  1418  1440 W NotificationService: Toast already killed. pkg=org.adaway callback=android.app.ITransientNotification$Stub$Proxy@faaae5e

**Comment by PerfectSlayer** [comment]
Hello @QingKongBaiYu 

Thansk for the report! I was observing the same behavior on my test device but not on my daily driver. I thought it was a device issue... But your report proves me it wasn't 😅 

I had a look to [the documentation](https://developer.android.com/training/data-storage) and decided to improve the file access using the new Storage Access Framework. I do no more have the issue and the app does no more need the `WRITE_EXTENAL_STORAGE` permission 👍 

The fix will be shipped in the next beta.
Regards
