### ISSUE TITLE
Adding new host and updating adaway original host source failed

### ISSUE THREAD

**Issue by gallegonovato** [AdAway/AdAway#2311]
**Describe the bug**
adaway does not support or more than 14 hosts or https://block.energized.pro/unified/formats/hosts.txt and failure to update the original adaway host source

**To Reproduce**
1. Go to adaway 
2. Click on add new host
3. Scroll down to añado https://block.energized.pro/unified/formats/hosts.txt and adaway doesn't add it. other times it adds it but instead of putting 15 lists. Keep putting that there are 14. And it closes or closes already installing it

**Expected behavior**

**Screenshots**

these are the ones i have

https://ibb.co/CKJPWsg , https://ibb.co/GCs9StH , https://ibb.co/dfC5201 , https://ibb.co/kDq49Cg

And here it looks like in the end he added it but instead of marking 15 host lists, it marks 14

https://ibb.co/4pHrKqs
https://ibb.co/RyN51Rg

**Device**
 - AdAway version: 5.0.10
 - Device: Nexus 6p, Nexus 5, oneplus
 - Android version: 17.1 of lineageos
 - Root version Magisk in its latest version

**Additional context**

I also think that mozilla, or fennec , fenix has this telemetry

affiliates-cdn.mozilla.org
crash-stats.mozilla.com
data.mozilla.com
detectportal.firefox.com
fhr.cdn.mozilla.net
fhr.data.mozilla.com
geo.mozilla.org
hang-reports.mozilla.org
hardware.metrics.mozilla.com
inconmig.telemetry.mozilla.org
input.mozilla.com
location.services.mozilla.com
metrics.mozilla.com
push.services.mozilla.com
reporter.mozilla.org
snippets.cdn.mozilla.net
snippets.mozilla.com
stun.services.mozilla.com
telemetry-experiment.cdn.mozilla.net
telemetry.mozilla.org
testpilot.mozillalabs.com
tiles.cdn.mozilla.net
tracking.services.mozilla.com

as they comment on https://forum.f-droid.org/t/fennec-f-droid-anti-features/11072/2 that could be added to the adaway host list

And if you allow me, I'll take advantage of the part about adding new hosts to be translated into Spanish. That is to say:

https://ibb.co/DYwH0Lm

**Comment by PerfectSlayer** [comment]
Hello @gallegonovato 

I do try your hosts sample and the application failed to parse and install it.
It seems it requires too much memory (RAM) to include it:

```2020-11-09 09:14:12.684 10580-10687/org.adaway E/AndroidRuntime: FATAL EXCEPTION: pool-5-thread-3
    Process: org.adaway, PID: 10580
    java.lang.OutOfMemoryError
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:590)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:669)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:727)
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:235)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:517)
        at org.adaway.model.source.SourceParser.parse(SourceParser.java:101)
        at org.adaway.model.source.SourceParser.<init>(SourceParser.java:44)
        at org.adaway.model.source.SourceModel.parseSourceInputStream(SourceModel.java:456)
        at org.adaway.model.source.SourceModel.downloadHostSource(SourceModel.java:420)
        at org.adaway.model.source.SourceModel.retrieveHostsSources(SourceModel.java:348)
        at org.adaway.ui.home.HomeViewModel.lambda$sync$2$HomeViewModel(HomeViewModel.java:161)
        at org.adaway.ui.home.-$$Lambda$HomeViewModel$j_0zmZEk5rhV-J-l8ERca_ZLZZA.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 4109144 byte allocation with 394424 free bytes and 385KB until OOM, target footprint 201326592, growth limit 201326592
        at java.util.Arrays.copyOf(Arrays.java:3136)
        at java.util.Arrays.copyOf(Arrays.java:3106)
        at java.util.ArrayList.grow(ArrayList.java:275)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
        at java.util.ArrayList.addAll(ArrayList.java:590)
        at java.util.stream.Collectors.lambda$toList$3(Collectors.java:231)
        at java.util.stream.-$$Lambda$Collectors$0y_EMl863H_U7B4kxyGscB4vAag.apply(Unknown Source:4)
        at java.util.stream.ReduceOps$3ReducingSink.combine(ReduceOps.java:174)
        at java.util.stream.ReduceOps$3ReducingSink.combine(ReduceOps.java:160)
        at java.util.stream.ReduceOps$ReduceTask.onCompletion(ReduceOps.java:754)
        at java.util.concurrent.CountedCompleter.tryComplete(CountedCompleter.java:578)
        at java.util.stream.AbstractTask.compute(AbstractTask.java:317)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:732)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I will see what I can do about it!
Thanks for the report.
