### ISSUE TITLE
Only touch actual hosts file once the app's work is "finalised" in a temp file

### ISSUE THREAD

**Issue by opusforlife2** [AdAway/AdAway#2563]
**Describe the bug**
Sometimes, Adaway can crash, leaving the hosts file in an unfinished state (such as half the size it's supposed to be). It seems like the app edits the hosts file directly, as you can see the numbers go up as sources are parsed. Why not have the app work on a temporary copy of the hosts file, and only copy it to the proper location after the file is properly built?

**To Reproduce**
1. Encounter an Adaway crash.
2. Open the folder containing the hosts file and check its size.
3. It is often 1/2 the size or less than what it is supposed to be.

**Expected behavior**
If Adaway crashes while in the middle of parsing hosts sources, it should not affect the actual file at all.

**Device**
 - AdAway version: 5.3.0

**Comment by PerfectSlayer** [comment]
Hello @opusforlife2 

This is already the case: https://github.com/AdAway/AdAway/blob/7301d723d4142cc1960b4b1db97a408c36348ece/app/src/main/java/org/adaway/model/root/RootModel.java#L94-L103

You can see it first creates the hosts file in the app storage location (` createNewHostsFile()`) then copies it to the system (`copyNewHostsFile()`).

So the error should come from elsewhere.
If you have a log cat of your crash, may be it could help. 

Regards

**Comment by opusforlife2** [comment]
Oh! That is reassuring. Thanks!

Sadly, the crash is always random. It never happens when I manually update the hosts file. But I haven't encountered this problem in several weeks, so I'll just close the issue for now and report back in case it crops up again.

**Comment by opusforlife2** [comment]
Another crash:

```
FATAL EXCEPTION: SourceLoader
Process: org.adaway, PID: 20274
java.io.UncheckedIOException: java.net.ProtocolException: unexpected end of stream
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:585)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:604)
	at org.adaway.model.source.SourceLoader$SourceReader.run(SourceLoader.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.ProtocolException: unexpected end of stream
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:430)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
	at okio.RealBufferedSource.read(RealBufferedSource.java:51)
	at okhttp3.internal.cache.CacheInterceptor$1.read(CacheInterceptor.java:175)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:263)
	at java.io.BufferedReader.fill(BufferedReader.java:172)
	at java.io.BufferedReader.readLine(BufferedReader.java:335)
	at java.io.BufferedReader.readLine(BufferedReader.java:400)
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:582)
	... 7 more
```

**Comment by opusforlife2** [comment]
Yet another type of crash, @PerfectSlayer:

```
FATAL EXCEPTION: SourceLoader
Process: org.adaway, PID: 6859
java.io.UncheckedIOException: java.net.SocketTimeoutException: timeout
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:585)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:604)
	at org.adaway.model.source.SourceLoader$SourceReader.run(SourceLoader.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.read(RealBufferedSource.java:51)
	at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:389)
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:427)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
	at okio.RealBufferedSource.read(RealBufferedSource.java:51)
	at okhttp3.internal.cache.CacheInterceptor$1.read(CacheInterceptor.java:175)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:263)
	at java.io.BufferedReader.fill(BufferedReader.java:172)
	at java.io.BufferedReader.readLine(BufferedReader.java:335)
	at java.io.BufferedReader.readLine(BufferedReader.java:400)
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:582)
	... 7 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 23 more
```

**Comment by PerfectSlayer** [comment]
Thanks for the reports.

They all look like to be related to network and I/O.
I will harden the related code to prevent the app to crash (it won't make you successfully fetch the source though 😓 )

**Comment by opusforlife2** [comment]
That's fine. Not crashing is still progress!
