### ISSUE TITLE
AdAway 6.1.0 (and 6.0.0) issues with root mode

### ISSUE THREAD

**Issue by arandomusertoo** [AdAway/AdAway#3818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Okay, so this is kind of a weird one.

I'm using an old tablet (GT-N5100) running Lineage 16 (Android 9) with Magisk 24.1.

Installing 6.1.0 initially gave an error about not being able to find the su binary (although it did trigger the magisk prompt and would notify that it was given superuser access).

Searching the issues closed issues I found #3269 and so I installed 6.0.0 which did let me get further (no error about the su binary), but gave an error applying the hosts file:

```java
04-18 03:53:20.544  4270  5281 W HomeViewModel: org.adaway.model.error.HostErrorException: An host error COPY_FAIL occurred
04-18 03:53:20.544  4270  5281 W HomeViewModel:         at org.adaway.model.root.RootModel.copyNewHostsFile(RootModel.java:171)
04-18 03:53:20.544  4270  5281 W HomeViewModel:         at org.adaway.model.root.RootModel.apply(RootModel.java:94)
04-18 03:53:20.544  4270  5281 W HomeViewModel:         at org.adaway.ui.home.HomeViewModel.lambda$sync$2(HomeViewModel.java:165)
04-18 03:53:20.544  4270  5281 W HomeViewModel:         at org.adaway.ui.home.HomeViewModel.$r8$lambda$j_0zmZEk5rhV-J-l8ERca_ZLZZA(HomeViewModel.java:0)
04-18 03:53:20.544  4270  5281 W HomeViewModel:         at org.adaway.ui.home.HomeViewModel$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
04-18 03:53:20.544  4270  5281 W HomeViewModel: Caused by: org.adaway.model.root.CommandException: Failed to remount hosts file partition as read-write.
04-18 03:53:20.544  4270  5281 W HomeViewModel:         at org.adaway.model.root.RootModel.copyHostsFile(RootModel.java:288)
04-18 03:53:20.544  4270  5281 W HomeViewModel:         at org.adaway.model.root.RootModel.copyNewHostsFile(RootModel.java:169)
``` 

I did confirm that the systemless hosts mount was active:
```java
/sbin/.magisk/block/data /system/etc/hosts ext4 rw,seclabel,relatime,errors=panic,user_xattr,barrier=1,journal_async_commit,data=ordered,noauto_da_alloc 0 0
``` 

At this point I gave up and installed the latest 5.x release which had no issues with detecting the su binary or applying the hosts file.

### Expected Behavior

To work.

### Device Configuration

- AdAway version: 
- Ad-blocker mode: 
- Device: 
- Android version: 
- Root version:

**Comment by momocat2** [comment]
I try root I thought It would work but the permissions is not showing. 
: android version 8.1 oreo
