### ISSUE TITLE
Nexus 5X - Nougat 7.1.2 - Segmentation fault - MITM

### ISSUE THREAD

**Issue by JimmyFellan** [AdAway/AdAway#883]
Hi guys,

when i start MITM on whole network, i got this error:

`Warning: linker: Warning: unable to normalize ""
Segmentation fault
at com.zimperium.zanti.zmitm.fragments.MITMServicePlugin.onPostIPTables(MITMServicePlugin.java:86)
at com.zimperium.zanti.plugins.ZHttpInjector.ZHttpInjectorService$ARPSpoofThread.run(ZHttpInjectorService.java:125)
`

Device: Nexus 5X
OS: Stock 7.1.2
Root: SuperSU
Recovery: TWRP

**Comment by jLynx** [comment]
I get the same
