### ISSUE TITLE
[CRASH] Looks like Oreo compatibility issue

### ISSUE THREAD

**Issue by DumF0rGaming** [AdAway/AdAway#994]
Every time I boot up my phone AdAway is crashing:

java.lang.RuntimeException: Unable to start receiver org.adaway.service.BootReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.adaway/.service.BootService }: app is in background uid UidRecord{830b71d u0a202 RCVR idle procs:1 seq(0,0,0)}
 at android.app.ActivityThread.handleReceiver(ActivityThread.java:3424)
 at android.app.ActivityThread.-wrap17(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1772)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6809)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.adaway/.service.BootService }: app is in background uid UidRecord{830b71d u0a202 RCVR idle procs:1 seq(0,0,0)}
 at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1522)
 at android.app.ContextImpl.startService(ContextImpl.java:1478)
 at android.content.ContextWrapper.startService(ContextWrapper.java:645)
 at android.content.ContextWrapper.startService(ContextWrapper.java:645)
 at org.adaway.service.BootReceiver.onReceive(BootReceiver.java:41)
 at android.app.ActivityThread.handleReceiver(ActivityThread.java:3410)
 ... 9 more

Autoupdates are enabled
AdAway v3.3
Oneplus 5T
Android 8.0
OOS Beta 3
Magisk v15.3

**Comment by DumF0rGaming** [comment]
Please take a look at this request
https://github.com/AdAway/AdAway/pull/961

**Comment by PerfectSlayer** [comment]
Thanks for the report.
I will release a fix for this crash "soon™️" 😉

**Comment by PerfectSlayer** [comment]
It should be fixed. I just uploaded [a dev build on XDA](https://forum.xda-developers.com/showpost.php?p=76438086&postcount=10983).
Feel free to test and report 😉
